before-script:
  script:
    - apt-get update && apt-get -y install nodejs npm
    - npm install --save @google-cloud/speech

job:
  image: ubuntu:18.04
  tags: 
    - docker
  script:
    - nodejs -v
